#
# kernel/fs/Makefile - 文件系统
#

obj-y := vfs_core.o vfs_buffer.o directory.o
obj-y += devfs.o dev_null.o dev_zero.o dev_console.o dev_fb.o dev_mouse.o
obj-y += procfs.o proc_cpuinfo.o proc_meminfo.o proc_uptime.o proc_version.o proc_pid.o
obj-y += fat32.o fat32_utils.o fat32_dir.o fat32_file.o fat32_lfn.o fat32_create.o fat32_vfs.o
obj-y += vfs.o super.o inode.o dcache.o file.o link.o chmod.o