#
# kernel/Makefile - 内核核心
#

# 本目录的对象文件
obj-y := main.o printk.o panic.o

# 子目录
obj-y += process/
obj-y += mm/
obj-y += fs/
obj-y += syscall/
obj-y += drivers/
obj-y += exec/
obj-y += net/
obj-y += ipc/

